name: Prettier

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Prettify code
      uses: creyD/prettier_action@31355f8eef017f8aeba2e0bc09d8502b13dbbad1 # v4.3
      with:
        prettier_options: --write **/*.{js,md}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
