name: Update docs
on:
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'authentication'
          fetch-depth: 1
      - uses: actions/checkout@v4
        with:
          repository: 'elfsquad/docs'
          fetch-depth: 1
          path: 'docs'
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - run: |
          npm i -g @elfsquad/tsdoc-parser
          tsdoc-parser $GITHUB_WORKSPACE/authentication/src/authentication/authenticationContext.ts authenticationContext.json AuthenticationContext

          echo "export default $(cat yourfile.js)" > temp && mv temp $GITHUB_WORKSPACE/docs/docs/configurator/libraries/methods/authenticationContext.ts
      - name: Commit, Push, and Create Pull Request
        run: |
          cd $GITHUB_WORKSPACE/docs
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git checkout -b update-authentication-context-docs
          git add .
          git commit -m "Update documentation for authentication context"
          git push --set-upstream origin update-authentication-context-docs
          gh pr create --title "Update Authentication Context Documentation" \
                       --body "This PR updates the documentation for the Authentication Context based on the latest changes." \
                       --label "documentation"
